---
- name: Make sure that the proserver user exists
  ansible.builtin.user:
    name: proserver

- name: Install PHP and extensions
  notify: Restart PHP-FPM
  ansible.builtin.apt:
    update-cache: yes
    name: >-
      {{
        ['php-fpm'] + php.install_extensions.items() |
        selectattr('1', 'eq', true)|map(attribute='0') |
        map('regex_replace', '^', 'php-') |
        list + (['composer'] if php.install_composer else [])
      }}

- name: Get PHP version
  changed_when: no
  register: php_version_full
  ansible.builtin.shell:
    cmd: >-
      php -r 'echo phpversion();' | grep -o '[0-9]\.[0-9]' | head -n1

- name: Set PHP version fact
  ansible.builtin.set_fact: 
    php_version: "{{ php_version_full.stdout }}"
