---
- name: Make sure that the proserver user exists
  ansible.builtin.user:
    name: proserver

- name: Install PHP and extensions
  notify: Restart PHP-FPM
  ansible.builtin.apt:
    name: >-
      {{
        ['php-fpm'] + php.install_extensions.items() |
        selectattr('1', 'eq', true)|map(attribute='0') |
        map('regex_replace', '^', 'php-') |
        list + (['composer'] if php.install_composer else [])
      }}
