---
- name: Set the PHP facts
  ansible.builtin.include_tasks: php_fact.yaml

- name: Manage apt repo (Ubuntu/Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: apt.yaml

- name: Install PHP and extensions (Ubuntu/Debian)
  when: ansible_os_family == 'Debian'
  ansible.builtin.include_tasks: install.yaml

- name: Set up phpfpmtop
  ansible.builtin.include_tasks: phpfpmtop.yaml

- name: Configure PHP-FPM
  ansible.builtin.include_tasks: phpfpm.yaml

- name: Configure PHP
  ansible.builtin.include_tasks: php.yaml

- name: Disable php-modules
  ansible.builtin.include_tasks: disable_modules.yaml
