---
- name: Template the overrides file
  community.general.ini_file:
    path: "{{ php.prefix.config }}/php/AAA-01-proserver.ini"
    create: no
    section: ''
    option: "{{ key }}"
    value: "{{ value }}"
    state: "{{ 'absent' if key is in php['php.ini'] else 'present' }}"
  loop_control:
    label: "{{ key }}={{ value }}"
  vars:
    key: "{{ item.0 }}"
    value: "{{ item.1 }}"
  loop: "{{ php_proserver_overrides | items() }}"
  when: "ansible_system == 'FreeBSD'"
  notify: Restart PHP-FPM
- name: Update PHP configuration
  community.general.ini_file:
    path: "{{ php_ini }}"
    create: no
    section: PHP
    option: "{{ key }}"
    value: "{{ value }}"
    state: "{{ 'absent' if value is none else 'present' }}"
  loop_control:
    label: "{{ php_ini }} {{ key }}={{ value }}"
  vars:
    php_ini: "{{ item.0 }}"
    key: "{{ item.1.0 }}"
    value: "{{ item.1.1 }}"
  loop: "{{ [php.prefix.config + '/php.ini', php.fpm.prefix.config + '/php.ini'] | unique | product(php['php.ini'].items()) | list }}"
  notify: Restart PHP-FPM
