---
- name: Check if the proserver overrides file exists
  register: aaa_proserver
  stat:
    path: "{{ php.prefix.config }}/php/AAA-01-proserver.ini"

- name: Disable the Proserver-specific PHP overrides 
  when: aaa_proserver.stat.exists
  replace:
    path: "{{ php.prefix.config }}/php/AAA-01-proserver.ini"
    regexp: '^([^;].*)$'
    replace: '; \1'
  notify: Restart PHP-FPM

- name: Update PHP configuration
  ini_file:
    path: "{{ php_ini }}"
    create: no
    section: PHP
    option: "{{ key }}"
    value: "{{ value }}"
    state: "{{ 'absent' if value is none else 'present' }}"
  loop_control:
    label: "{{ php_ini }} {{ key }}={{ value }}"
  vars:
    php_ini: "{{ item.0 }}"
    key: "{{ item.1.0 }}"
    value: "{{ item.1.1 }}"
  loop: "{{ [php.prefix.config + '/php.ini', php.fpm.prefix.config + '/php.ini']|unique|product(php['php.ini'].items())|list }}"
  notify: Restart PHP-FPM
