---
- name: Update apt cache (Debian-based)
  when: "ansible_os_family == 'Debian'"
  ansible.builtin.apt:
    update_cache: yes

- name: Get PHP version
  changed_when: no
  register: php_version_full
  check_mode: no
  ansible.builtin.shell:
    cmd: >-
      {%- if ansible_os_family == 'Debian' -%}
      apt-cache search --names-only "^php[0-9].[0-9]$" | grep -o '[0-9]\.[0-9]'
      {%- elif ansible_os_family == 'FreeBSD' -%}
      # PHP is already installed on the Proserver hosts, no need to query the packages
      php -r 'echo phpversion();' | grep -o '[0-9]\.[0-9]' | head -n1
      {%- else -%}
      echo "Unsupported OS" && exit 1
      {%- endif -%}

- name: Set PHP version fact
  ansible.builtin.set_fact:
    php_version: "{{ php_version_full.stdout }}"

- name: Set the PHP FPM service name fact
  when: "ansible_os_family == 'FreeBSD' and ansible_local.proserver is defined"
  ansible.builtin.set_fact:
    php: "{{ php | ansible.builtin.combine({'fpm': {'service': php_fpm_service_name}}) }}"
  vars:
    blueprint: "{{ ansible_local.proserver.blueprint }}"
    blueprint_date: "{{ blueprint.year }}.{{ blueprint.quarter }}.blueprint_version }}"
    php_fpm_service_name: >-
      {{ "php_fpm" if blueprint_date is version('24.4.1', '>=') else "php-fpm" }}
