---
- name: Enable PHP-FPM status API
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: "^;?pm\\.status_path[\\s\\t]*="
    line: "pm.status_path = /php-fpm/status"
  with_items: "{{ php.fpm.pools.keys() | map('regex_replace', '^(.*)$', php.fpm.prefix.pool_config + '/\\1.conf') | list }}"
  notify: Restart PHP-FPM

- name: Create install dir for phpfpmtop
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: proserver
    group: proserver
    mode: "0755"
  with_items:
    - /var/www/bin

- name: Install phpfpmtop
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.get_url:
    url: "{{ php.phpfpmtop.release.url }}"
    checksum: "{{ php.phpfpmtop.release.checksum }}"
    dest: "{{ item }}"
    mode: "0755"
  with_items:
    - /var/www/bin/phpfpmtop
  # Workaround for issues with NAT64 gateway
  retries: 5
  delay: 2

- name: Configure phpfpmtop
  vars:
    php_phpfpmtop_config_file: /var/www/.phpfpmtop.conf
  loop:
    - section: default
      option: listen
      value: '"{{ php.fpm.pools.www.listen }}"'
    - section: default
      option: status
      value: '"/php-fpm/status"'
  loop_control:
    label: "{{ php_phpfpmtop_config_file }} {{ item.section }}[{{ item.option }}]={{ item.value }}"
  community.general.ini_file:
    path: "{{ php_phpfpmtop_config_file }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: proserver
    group: proserver
    mode: "0644"
