---
- name: Update PHP-FPM configuration
  community.general.ini_file:
    path: "{{ php_fpm_conf }}"
    create: yes
    section: "{{ item.pool }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    owner: root
    mode: "0644"
  loop_control:
    label: "{{ php_fpm_conf }} {{ item.option }}={{ item.value }}"
  vars:
    php_fpm_conf: "{{ php.fpm.prefix.pool_config }}/www.conf"
  loop: "{{ php.fpm.pools | php_fpm_config_merge }}"
  notify: Restart PHP-FPM
