---
- name: Get PHP version
  changed_when: no
  register: php_version_full
  check_mode: no
  ansible.builtin.shell:
    cmd: >-
      {%- if ansible_os_family == 'Debian' -%}
      apt update &&
      apt-cache search --names-only "^php[0-9].[0-9]$" |  awk '{print $1}'
      {%- elif ansible_os_family == 'FreeBSD' -%}
      # PHP is already installed on the Proserver hosts, no need to query the packages
      php -r 'echo phpversion();' | grep -o '[0-9]\.[0-9]' | head -n1
      {%- else -%}
      echo "Unsupported OS" && exit 1
      {%- endif -%}

- name: Set PHP version fact
  ansible.builtin.set_fact:
    php_version: "{{ php_version_full.stdout }}"
