---
- name: Copy Xdebug toggle script
  ansible.builtin.copy:
    src: "xdebug"
    dest: /usr/local/bin/xdebug
    mode: "0755"

- name: Disable Xdebug
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "0644"
    owner: root
  loop_control:
    label: "{{ item.path }}"
  with_items:
    - path: /usr/local/etc/php/ext-20-xdebug.ini
      state: absent
