---
- name: Converge
  hosts: all
  environment:
    GITHUB_ACTIONS: "maybe"
    ANSIBLE_HASH_BEHAVIOUR: merge
  vars:
    system:
      features:
        proserver_user: yes
    nginx:
      default_server: no
    php:
      version: 8.1
      repository:
        apt:
          enabled: yes
  tasks:
    - name: Include ansible-proserver-system
      ansible.builtin.include_role:
        name: system

    - name: Include ansible-proserver-nginx
      ansible.builtin.include_role:
        name: nginx

    - name: "Include ansible-proserver-php"
      ansible.builtin.include_role:
        name: "ansible-proserver-php"
