---
- name: Verify
  hosts: all
  vars:
    php:
      modules:
        disable:
          cli:
            - exif
            - tokenizer
  tasks:
    - name: Create the current_release folder
      ansible.builtin.file:
        dest: "{{ item }}"
        state: directory
        owner: proserver
        mode: "0755"
      loop:
        - /var/www
        - /var/www/current

    - name: Template the example Nginx config
      ansible.builtin.template:
        owner: root
        mode: "0644"
        src: nginx/http.d/app.conf
        dest: "/etc/nginx/http.d/app.conf"

    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Copy the example PHP script
      ansible.builtin.copy:
        owner: proserver
        mode: "0777"
        src: "index.php"
        dest: "/var/www/current/index.php"

    - name: Test PHP-FPM
      block:
        - name: Check that a page returns successfully but fail if 'Hello PHP {{ ansible_local.php.version }}!' is not in the page contents
          ansible.builtin.uri:
            url: http://localhost
            return_content: true
          register: this
          failed_when: this is failed or ('Hello PHP ' + ansible_local.php.version) not in this.content
      rescue:
        - name: Get nginx error log
          register: nginx_log
          changed_when: no
          ansible.builtin.command:
            cmd: tail -n 10 /var/log/nginx/error.log

        - name: Display the log output
          ansible.builtin.fail:
            msg: "{{ nginx_log.stdout }}"

    - name: Test PHP disabled modules
      become_user: proserver
      become: yes
      register: php_enabled_modules
      changed_when: no
      ansible.builtin.shell:
        executable: /bin/bash
        cmd: source ~/.shrc && php -m

    - name: Fail if tokenizer and exif are enabled
      when: "'tokenizer' in php_enabled_modules.stdout or 'exif' in php_enabled_modules.stdout"
      ansible.builtin.fail:
        msg: "tokenizer and exif are still enabled!"
