#!/usr/bin/env python3.6
import sys
import os
from subprocess import check_call
from subprocess import DEVNULL


def toggle_file(file_path, content):
    if os.path.isfile(file_path):
        os.unlink(file_path)
        return False

    with open(file_path, 'w') as file:
        file.write(content)

    return True


if __name__ == '__main__':
    if os.geteuid() != 0:
        sys.exit(check_call(['sudo', '--', sys.executable] + sys.argv))
    new_state = toggle_file('/usr/local/etc/php/ext-20-xdebug.ini',
                            """zend_extension=xdebug.so
                        
[xdebug]
xdebug.max_nesting_level = 500
xdebug.remote_enable = On
xdebug.remote_connect_back = On
xdebug.remote_autostart = On
xdebug.remote_log = /var/log/php/xdebug.log
""")
    if check_call(["service", "php-fpm", "restart"], stdout=DEVNULL, stderr=DEVNULL) == 0:
        print('Xdebug is now %s' % ('enabled' if new_state else 'disabled'))
