---
name: Test
run-name: Run molecule tests on the role
on:
  push:
  workflow_dispatch:

env:
  ANSIBLE_ROLES_PATH: roles
  ANSIBLE_HASH_BEHAVIOUR: merge

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: pip install -r requirements.txt

      - name: Run ansible-lint
        run: "ansible-lint"

  molecule:
    strategy:
      matrix:
        os: [ubuntu-2204, ubuntu-2404, debian-12]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies.
        run: |
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml

      - name: Run molecule
        run: molecule test -p ${{ matrix.os }}
